#' @title
#' Title
#'
#' @description
#' Description of function
#'
#' @details
#' Details of function (optional)
#'
#' @param argument description add more as needed
#'
#' @param argument description add more as needed
#'
#' @return
#' what is the output
#'
#' @export

fs_proj <- function(path, ...) {
  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # generate header for file
  header <- c(
    "# This file was generated by a call to 'ptexamples::hello_world()'.",
    "# The following inputs were received:",
    ""
  )

  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "INDEX"))

  # # set file structure
  # structure <- c("01_data", "02_src", "03_outputs")
  #
  # # add folders based on structure
  # for (i in 1:length(structure)) {
  #   dir.create(glue::glue("{path}/{structure[i]}"))
  # }
  #
  # FSsetup::create_fs_readme(type = "project",
  #                           format = readme_format,
  #                           file_path = path)

}
